name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.38f919b7ca847792d5b342b40f4e9adaf706dbac }}
          project_id: "generatrade"

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/generatrade/generatrade-app:$GITHUB_SHA .
          docker push gcr.io/generatrade/generatrade-app:$GITHUB_SHA

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v2
        with:
          namespace: default
          cluster_name: generatrade-cluster
          gcp_sa_key: ${{ secrets.38f919b7ca847792d5b342b40f4e9adaf706dbac }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment/kubernetes/configmap.yaml
          kubectl apply -f deployment/kubernetes/deployment.yaml
          kubectl apply -f deployment/kubernetes/service.yaml
