steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/generatrade/generatrade-app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/generatrade/generatrade-app:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment/kubernetes']
images:
  - 'gcr.io/generatrade/generatrade-app:$COMMIT_SHA'
