# backtesting_config.yaml

backtesting:
  initial_capital: 10000
  transaction_cost: 0.001  # Transaction cost as a fraction (e.g., 0.001 for 0.1%)
  train_test_split: 0.7    # Fraction of data for in-sample (training)

evaluation_metrics:
  sharpe_ratio: true
  sortino_ratio: true
  max_drawdown: true
  annualized_volatility: true

parameter_optimization:
  enabled: true
  parameter_grid:
    transaction_cost: [0.0005, 0.001, 0.002]
    initial_capital: [5000, 10000, 20000]
