# deployment_config.yaml

cloud_provider: "GCP"  # Options: GCP, AWS, Azure

gcp:
  project_id: "${GCP_PROJECT_ID}"
  region: "us-central1"
  container_registry: "gcr.io/${GCP_PROJECT_ID}"
  cloud_run_service: "trading-system-service"

kubernetes:
  cluster_name: "trading-cluster"
  region: "us-central1"
  node_count: 3
  node_machine_type: "e2-standard-4"

docker:
  image_name: "trading-system"
  tag: "latest"
