# File: data_pipeline/config/strategies.yaml
strategies:
  - name: "RSI Strategy"
    required_data:
      - "Market_Data"
    required_indicators:
      - "RSI"
  - name: "MACD Strategy"
    required_data:
      - "Market_Data"
    required_indicators:
      - "MACD"
  - name: "ML Model Strategy"
    required_data:
      - "Market_Data"
    required_features:
      - "Pct_Change"
      - "Volatility"
