strategy:
  name: "Breakout"
  parameters:
    breakout_period: 20
    stop_loss: 0.12
    take_profit: 0.18
  objectives:
    - name: "High Risk, Short Term"
    - name: "High Risk, Long Term"
  constraints:
    max_drawdown: 0.20
    risk_tolerance: "high"
