strategy:
  name: "Mean Reversion"
  parameters:
    rsi_period: 14
    entry_threshold: 30
    exit_threshold: 70
    stop_loss: 0.05
    take_profit: 0.10
  objectives:
    - name: "Low Risk, Short Term"
    - name: "High Risk, Short Term"
  constraints:
    max_drawdown: 0.10
    risk_tolerance: "low"
