strategy:
  name: "Pairs Trading"
  parameters:
    correlation_threshold: 0.85
    spread_entry: 1.5
    spread_exit: 0.5
    stop_loss: 0.10
    take_profit: 0.12
  objectives:
    - name: "Low Risk, Long Term"
    - name: "Low Risk, Short Term"
  constraints:
    max_drawdown: 0.10
    risk_tolerance: "low"
 